### ISSUE TITLE
which version of pysam do you test in the development of deeptools

### ISSUE THREAD

**Issue by carl-** [fidelram/deepTools#357]
> bamCoverage --normalizeUsingRPKM --extendReads 300 -b in.bam -o out.bw
Traceback (most recent call last):
  File "/usr/bin/bamCoverage", line 7, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/deeptools/bamCoverage.py", line 246, in main
    verbose=args.verbose,
  File "/usr/lib/python2.7/site-packages/deeptools/countReadsPerBin.py", line 169, in __init__
    verbose=verbose)
  File "/usr/lib/python2.7/site-packages/deeptools/getFragmentAndReadSize.py", line 96, in get_read_and_fragment_length
    verbose=verbose)
  File "/usr/lib/python2.7/site-packages/deeptools/mapReduce.py", line 150, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
AttributeError: 'pysam.csamtools.AlignedRead' object has no attribute 'template_length'
=========================
I always get such error message since I upgrade deeptools from v1.5.13 to any version above 2.0. I also tried pysam version from 0.8.4 to 0.9.0, all of them give me this error. 

my OS is centos 7 x86_64.
currently I have to use the old deeptools v 0.5.13, please help

**Comment by fidelram** [comment]
Deeptools requires pysam > 0.8.2 otherwise you get the error you are
mention.

For what you describe, it seems that there is a pysam < 0.8 installation in
you computer that takes precedence even if you install a newer version of
pysam

Try:

$ pip uninstall pysam

then in the python shell:

import pysam
pysam.__version__
pysam.__file__

That will tell you if there is another pysam and where.

Best,

Fidel


On Wed, May 4, 2016 at 4:12 AM, WEI ZH <notifications@github.com> wrote:

> bamCoverage --normalizeUsingRPKM --extendReads 300 -b in.bam -o out.bw
> Traceback (most recent call last):
> File "/usr/bin/bamCoverage", line 7, in
> main()
> File "/usr/lib/python2.7/site-packages/deeptools/bamCoverage.py", line
> 246, in main
> verbose=args.verbose,
> File "/usr/lib/python2.7/site-packages/deeptools/countReadsPerBin.py",
> line 169, in *init*
> verbose=verbose)
> File
> "/usr/lib/python2.7/site-packages/deeptools/getFragmentAndReadSize.py",
> line 96, in get_read_and_fragment_length
> verbose=verbose)
> File "/usr/lib/python2.7/site-packages/deeptools/mapReduce.py", line 150,
> in mapReduce
> res = pool.map_async(func, TASKS).get(9999999)
> File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
> raise self._value
> AttributeError: 'pysam.csamtools.AlignedRead' object has no attribute
> 'template_length'
>
> I always get such error message since I upgrade deeptools from v1.5.13 to
> any version above 2.0. I also tried pysam version from 0.8.4 to 0.9.0, all
> of them give me this error.
>
> my OS is centos 7 x86_64.
> currently I have to use the old deeptools v 0.5.13, please help
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/357>
>



-- 

Fidel Ramirez

**Comment by carl-** [comment]
thank you . I have got rid of that error message according to your suggestion
